### ISSUE TITLE
Errores en consola

### ISSUE THREAD

**Issue by bifacil** [bifacil/Serraclara#13]
Hay un error en ambas web que supongo que serán fáciles de corregir:

![image](https://user-images.githubusercontent.com/4572969/157675129-80b4938c-e379-4501-8b8b-3fdf748e5282.png)

![image](https://user-images.githubusercontent.com/4572969/157675213-c348c2fb-55e4-4389-954b-2f552bcca529.png)

Aunque no tenga nada que ver, arrelaremos esto de Calendas en este mismo issue:

![image](https://user-images.githubusercontent.com/4572969/157675622-31ef1be6-3eda-4055-a926-73fdb8e4793b.png)

**Comment by VindigniGabriel** [comment]
[Eliminado ejemplos de Api Page](https://github.com/bifacil/www.calendas.net/commit/a090271c53ca75d26fe47affe040ddebcdaa6864)

**Comment by bifacil** [comment]
ok
